---
- name: Instalar y configurar servidor FTP en Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Instalar el servicio vsftpd
      apt:
        name: vsftpd
        state: present

    - name: Configurar vsftpd
      template:
        src: vsftpd.conf.j2
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: 0644
        notify: Reiniciar vsftpd

    - name: Iniciar el servicio
      service:
        name: vsftpd
        enabled: yes
        state: started

    - name: Crear usuario
      user:
        name: ftpuser
        password: "Admin_123"
        shell: /bin/bash

    - name: Crear directorio para el usuario
      file:
        path: /home/ftpuser/ftp
        state: directory
        owner: ftpuser
        group: ftpuser
        mode: '0755'
